apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "zulip.fullname" . }}-post-setup-scripts"
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
data:
  {{- range $scriptName, $scriptContents := .Values.postSetup.scripts }}
  {{ $scriptName }}: |
    {{- $scriptContents | nindent 4 }}
  {{- end }}

