apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-redis-password"
  labels: {{- include "zulip.labels" . | nindent 4 }}
data:
  something: "requirepass {{ .Values.redis.password }}"
