apiVersion: v1
kind: Service
metadata:
  name: {{ include "zulip.fullname" . }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.zulip.environment.CERTIFICATES }}
      targetPort: https
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "zulip.selectorLabels" . | nindent 4 }}
