apiVersion: v2
description: Zulip is an open source threaded team chat that helps teams stay productive and focused.
name: zulip
type: application
icon: https://raw.githubusercontent.com/zulip/zulip/main/static/images/logo/zulip-icon-square.svg
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.4.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "6.1-0"
dependencies:
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    tags:
      - memcached
    version: 6.0.16
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
    version: 8.32.0
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: 16.8.7
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    # Note: values.yaml overwrites posgresql image to zulip/zulip-postgresql:14
    version: 11.1.22

sources:
  - https://github.com/zulip/zulip
  - https://github.com/zulip/docker-zulip
  - https://github.com/orgs/zulip/packages/container/package/zulip
