apiVersion: v2
description: A chat for distributed teams which combines the immediacy of real-time chat with an email threading model. With Zulip, you can catch up on important conversations while ignoring irrelevant ones. 
name: zulip
type: application
icon: https://raw.githubusercontent.com/zulip/zulip/main/static/images/logo/zulip-icon-square.svg
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "4.7-0"
dependencies:
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    tags:
      - memcached
    version: 5.15.10
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
    version: 8.24.12
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: 15.5.5
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    version: 10.13.14

sources:
  - https://github.com/zulip/zulip
  - https://github.com/zulip/docker-zulip
  - https://hub.docker.com/r/zulip/docker-zulip
