apiVersion: v2
description: Zulip is an open source threaded team chat that helps teams stay productive and focused.
name: zulip
type: application
icon: https://raw.githubusercontent.com/zulip/zulip/main/static/images/logo/zulip-icon-square.svg
maintainers:
  - name: zulip
    url: https://chat.zulip.org/
## This is the chart version. This version number should be
## incremented each time you make changes to the chart and its
## templates, including the app version.  Versions are expected to
## follow Semantic Versioning (https://semver.org/)
version: 1.11.40

## This is the version number of the application being deployed. This
## version number should be incremented each time you make changes to
## the application. Versions are not expected to follow Semantic
## Versioning. They should reflect the version the application is
## using.  It is recommended to use it with quotes.
appVersion: "11.4-0"
dependencies:
  - name: memcached
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - memcached
    version: 8.1.5
  - name: rabbitmq
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - rabbitmq
    version: 16.0.14
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - redis
    version: 23.2.12
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - postgresql
    ## Note: values.yaml overwrites posgresql image to zulip/zulip-postgresql:14
    version: 18.1.8

sources:
  - https://github.com/zulip/zulip
  - https://github.com/zulip/docker-zulip
  - https://hub.docker.com/r/zulip/docker-zulip
