---
# Test: CERTIFICATES set to non-empty switches Service targetPort to
# https.
zulip:
  password: test-password
  environment:
    SETTING_ZULIP_ADMINISTRATOR: "admin@example.com"
    SETTING_EXTERNAL_HOST: zulip.example.com
    CERTIFICATES: self-signed

memcached:
  memcachedPassword: test-memcached
rabbitmq:
  auth:
    password: test-rabbitmq
    erlangCookie: test-cookie
redis:
  auth:
    password: test-redis
postgresql:
  auth:
    postgresqlPassword: test-pg-admin
    password: test-pg-zulip
