---
# Test: ServiceAccount with custom annotations.
zulip:
  password: test-password
  environment:
    SETTING_ZULIP_ADMINISTRATOR: "admin@example.com"
    SETTING_EXTERNAL_HOST: zulip.example.com

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::role/zulip"
  name: custom-zulip-sa

memcached:
  memcachedPassword: test-memcached
rabbitmq:
  auth:
    password: test-rabbitmq
    erlangCookie: test-cookie
redis:
  auth:
    password: test-redis
postgresql:
  auth:
    postgresqlPassword: test-pg-admin
    password: test-pg-zulip
