---
# Test: Environment variables using valueFrom (Kubernetes Secret refs).
zulip:
  password: test-password
  environment:
    SETTING_ZULIP_ADMINISTRATOR: "admin@example.com"
    SETTING_EXTERNAL_HOST: zulip.example.com
    SECRETS_email_password:
      valueFrom:
        secretKeyRef:
          name: zulip-email-secret
          key: password

memcached:
  memcachedPassword: test-memcached
rabbitmq:
  auth:
    password: test-rabbitmq
    erlangCookie: test-cookie
redis:
  auth:
    password: test-redis
postgresql:
  auth:
    postgresqlPassword: test-pg-admin
    password: test-pg-zulip
